config/routes.rb
Notes::Application.routes.draw do
  get 'home/index'

  scope :api do
    get '/notes(.:format)' => 'notes#index'
    post '/notes(.:format)' => 'notes#new'
    get '/note/:id(.:format)' => 'notes#show'
    post '/note/:id(.:format)' => 'notes#update'
    delete '/note/:id(.:format)' => 'notes#destroy'
  end

  root to: 'home#index'

  

end

app/models/note.rb
class Note < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  def verified_request?
    if request.content_type == "application/json"
      true
    else
      super()
    end
  end
  #todo Разобраться
  #protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    render json:  Note.select(:id, :title, :created_at)
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
    render json: Note.find(params[:id])
  end

  # GET /notes/new
  def new
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.json { render json: @note.to_json }
      else
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render action: 'show', status: :created, location: @note }
      else
        format.html { render action: 'new' }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render json: @note.to_json }
      else
        format.html { render action: 'edit' }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/home/index.html.erb
<div ng-controller="NotesCtrl">
  <div class="col-lg-8">
    <div ng-show="selectedNote" ng-hide="editingNote">
      <h2>{{ selectedNote.title }}</h2>
      <p>{{ selectedNote.body }}</p>
      <button type="button" class="btn btn-primary" ng-click="editNote(selectedNote.id)">
        Edit!
      </button>
    </div>
    <div ng-show="editingNote" ng-hide="selectedNote">
      <input class="" type="text" ng-model="title">
      <textarea ng-model="text"></textarea>
      <button type="button" class="btn btn-success" ng-click="saveNote(id)">
        Save
      </button>
      <button type="button" class="btn btn-danger" ng-click="showNote(id)">
        Cancel!
      </button>
    </div>
    </div>
  <div class="col-lg-4">
    <ul>
      <li ng-repeat="note in notes" class="pointer">
        <span ng-click="showNote(note.id)">
            <h3>{{ note.title }}</h3>
            <small>{{ note.created_at| date: 'medium'}}</small>
        </span>
        <button type="button" class="btn btn-danger" ng-click="deleteNote(note.id)">
          Delete
        </button>
      </li>
    </ul>
    <button type="button" class="btn btn-primary" ng-click="editNote()">
      New
    </button>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="Notes">
<head>
  <title>Notes</title>
  <%= stylesheet_link_tag    "application", media: "all"%>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.0.6/angular.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.0.6/angular-resource.min.js"></script>
<%= javascript_include_tag "application" %>
</body>
</html>

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<h1>Listing notes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.title %></td>
        <td><%= note.body %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @note.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @note.body %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>